### PR TITLE
Mark pointer parameters we don't change as const

### PR DESCRIPTION
**Pull request by vpodzime**
Otherwise the caller cannot tell if we are going to change the referenced
value/data or not.

Note: Requested in the issue #56

### CODE REVIEW

**Comment by vpodzime** [comment]
A tip for doing the review of these changes - it might be best to just go through the [plugins' header files](https://github.com/vpodzime/libblockdev/tree/master-const_params_pr/src/plugins) and check that all pointer parameters that you feel like they should be ``const`` are ``const``. The correctness of the rest of the changes should be assured by the fact that it all compiles and the tests pass.

**Comment by vojtechtrefny** [comment]
Looks good to me.

**Comment by snbueno** [comment]
Other than the two params in bd_kbd_zram_create_devices() from src/plugins/kbd.h that we discussed in IRC (which should also be marked const), this looks fine to me as well.

**Comment by vpodzime** [comment]
> Other than the two params in bd_kbd_zram_create_devices() from src/plugins/kbd.h that we discussed in IRC (which should also be marked const), this looks fine to me as well.

Fixed, thanks!

**Pull request merged**
