### PR TITLE
Support for extra arguments

### PR DESCRIPTION
**Pull request by vpodzime**
For now only for functions that can actually do something with them. Before the time for ``libblockdev-2.0`` comes we will decide whether all functions should take extra arguments or not.

### CODE REVIEW

**Comment by dwlehman** [comment]
Looks good to me.

**Comment by vpodzime** [comment]
Added the support for extra arguments and while doing so I realized that the ``bcache_create`` function had the arguments in a wrong order so I fixed that too.

**Comment by dwlehman** [comment]
Still looks good to me.

**Comment by vpodzime** [comment]
Added one little improvement to the code transforming the ``**kwargs`` so that ``None`` is passed instead of ``[]`` if there are none extra arguments nor ``**kwargs`` specified.

**Pull request merged**
