### PR TITLE
Add pv_free to BDLVMPVdata

### PR DESCRIPTION
**Pull request by vojtechtrefny**

### CODE REVIEW

**Comment by dwlehman** [comment]
I don't object, but I'm curious what this is for. It seems like this is going to be a required piece of information if we ever add support for user-specified pv subsets for new lvs.

**Comment by vpodzime** [comment]
Exactly. And for LVM RAID, also for LVM cache support in blivet-gui and also to prevent issues with calling ``pvmove()`` on PVs with no data. Generally a useful piece of information, I think.

**Comment by vpodzime** [comment]
A test for this new info would be nice, but considering the fact how ``pvinfo()`` and ``pvs()`` tests look like right now I think we can deal with all that together at some point in the future.

**Comment by vpodzime** [comment]
Looks good to me otherwise.

**Pull request merged**
